export const SET_TOKEN = "CONTENT.SET_TOKEN";
export const SET_MOVIES = "CONTENT.SET_MOVIES";
export const TOGGLE_FAVORITE = "CONTENT.TOGGLE_FAVORITE";
export const REMOVE_FAVORITE = "CONTENT.REMOVE_FAVORITE";
export const ADD_FAVORITE = "CONTENT.ADD_FAVORITE";
